### PR TITLE
fix: Remove streching from home icons

### LINKED ISSUE #52: Bug: Home screen icons are stretched
CSS for `` on home screen doesn't include `object-fit: contain` making icons stretched:

Now:
image

Desired:
image

### PR DESCRIPTION
**Pull request by SamoKopecky**
Resolves #52 
SSIA

### CODE REVIEW

File: packages/app/src/components/home/HomePage.tsx [hunk 1]
```diff
@@ -60,6 +60,7 @@ const useCatalogStyles = makeStyles({
     '& img': {
       height: 80,
       width: 80,
+      "object-fit": 'contain',
```
Comment (tumido) [inline packages/app/src/components/home/HomePage.tsx:63]: This should be `objectFit`, since it's JSS. `jss-camel-case` plugin doesn't complain in this particular version, however if Backstage ever updates to MUI v5, it will start raising warnings.

**Review by tumido — CHANGES_REQUESTED** [review]

File: packages/app/src/components/home/HomePage.tsx (hunk 1 above)
Comment (SamoKopecky) [reply packages/app/src/components/home/HomePage.tsx]: Resolved in the latest commit.

File: packages/app/src/components/home/HomePage.tsx [hunk 2]
```diff
@@ -60,6 +60,7 @@ const useCatalogStyles = makeStyles({
     '& img': {
       height: 80,
       width: 80,
+      'objectFit': 'contain',
```
Comment (tumido) [inline packages/app/src/components/home/HomePage.tsx:63]: nit: quotes are not necessary on the key here, please remove

**Review by tumido — CHANGES_REQUESTED** [review]

File: packages/app/src/components/home/HomePage.tsx (hunk 2 above)
Comment (SamoKopecky) [reply packages/app/src/components/home/HomePage.tsx]: Fixed in the lasest commit.
